In [159]:
import numpy as np
import torch
from torch import nn
import torch.utils.data as Data
from torch.utils.data import DataLoader
import string
import pandas as pd

# Reference:

https://blog.floydhub.com/long-short-term-memory-from-zero-to-hero-with-pytorch/

In [160]:
def letters(input):
    valids = []
    last_space = False
    for character in input:
        if character.isalpha():
            last_space = False
            valids.append(character)
        else:
            if last_space:
                continue
            last_space=True
            valids.append(" ")
    return ''.join(valids)

In [161]:
with open("./data/anna.txt") as file:
    text = letters(file.read().lower().strip()).strip()

In [162]:
words = np.array(text.split(" "))

In [163]:
alpha = {}

for i,a in enumerate(list(string.ascii_lowercase)):
    alpha[a] = i
    
alpha[" "] = 26

def hot_encoded(c):
    ix = alpha[c]
    arr = np.zeros(len(alpha.keys()),dtype = "uint8")
    arr[ix] = 1
    return arr

In [164]:
words

array(['chapter', 'happy', 'families', ..., 'about', 'new', 'ebooks'],
      dtype='<U19')

In [165]:
data = []
labels = []

In [166]:
txt_len = len(text)

for i,c in enumerate(text):
    if i == txt_len-1:
        break
    X_hot = hot_encoded(c)
    y_hot = hot_encoded(text[i+1])
    data.append(X_hot)
    labels.append(y_hot)

In [167]:
data = np.array(data)
labels = np.array(labels)

In [168]:
labels

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [192]:
X_train_tensor = torch.from_numpy(data).float()
y_train_tensor =  torch.from_numpy(labels).float()

#train_data = Data.TensorDataset(X_train_tensor,y_train_tensor)

In [170]:
next(iter(train_data))

(tensor([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0], dtype=torch.uint8),
 tensor([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0], dtype=torch.uint8))

In [198]:
model = nn.Sequential(
nn.LSTM(len(data[0]),1,1,dropout=0.3,batch_first=True)
)

In [199]:
t

tensor([[[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0]]], dtype=torch.uint8)

In [260]:
chars,lbls = next(iter(train_data))
tc = chars.reshape(1,1,len(data[0]))
tl = lbls.reshape(1,1,len(data[0]))

input_dim = 27
hidden_dim = 27
n_layers = 1

l = nn.LSTM(input_dim,hidden_dim,n_layers,batch_first=True)
hidden = (tl,tl)

l(tc,hidden)

RuntimeError: Expected object of scalar type Byte but got scalar type Float for argument #3 'mat2' in call to _th_addmm_out

In [266]:
batch_size = 1
seq_len = 1

input_dim = 5
hidden_dim = 10
n_layers = 1

lstm_layer = nn.LSTM(input_dim, hidden_dim, n_layers, batch_first=True)

inp = torch.randn(batch_size, seq_len, input_dim)
hidden_state = torch.randn(n_layers, batch_size, hidden_dim)
cell_state = torch.randn(n_layers, batch_size, hidden_dim)
hidden = (hidden_state, cell_state)

out, hidden = lstm_layer(inp, hidden)

In [265]:
hidden[0].shape

torch.Size([1, 1, 10])

In [258]:
hidden[1].shape

torch.Size([1, 1, 10])

In [262]:
inp

tensor([[[ 0.1498, -0.6445, -0.4008,  1.4507,  1.3185]]])

In [249]:
tc

tensor([[[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0]]], dtype=torch.uint8)

In [261]:
tl

tensor([[[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0]]], dtype=torch.uint8)